# Generated by Django 3.1.2 on 2021-01-07 14:26

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_institution', models.CharField(max_length=255)),
                ('date_of_establishment', models.DateField()),
                ('company_logo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=255)),
                ('date_of_manufacturing', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_reg.institutioninfo')),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=15, unique=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_reg.myuser')),
            ],
        ),
        migrations.AddField(
            model_name='institutioninfo',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_reg.myuser'),
        ),
    ]
