# Generated by Django 3.1.2 on 2021-01-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdQRGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_reg.product')),
            ],
        ),
    ]
