# Generated by Django 3.1.2 on 2021-01-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodqrgen',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/'),
        ),
    ]
