# Generated by Django 3.1.2 on 2021-01-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0002_prodqrgen_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodqrgen',
            name='qr_code',
        ),
    ]
