# Generated by Django 3.1.2 on 2021-01-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0004_prodqrgen_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodqrgen',
            name='logo',
        ),
    ]
